CREATE TABLE DimStop (
    StopSK INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DimStop PRIMARY KEY,
    StopID INT NOT NULL,
    PlaceName NVARCHAR(100) NOT NULL,
    ActivityDescription NVARCHAR(100) NOT NULL,
    ArrivalTime DATETIME NOT NULL,
    StopDuration INT DEFAULT 0
);
GO